name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & push the Docker image
      run: |
         echo "${{ secrets.CANISTER_PW }}" | docker login -u "saderi" --password-stdin cloud.canister.io:5000
         docker build . --file Dockerfile --tag cloud.canister.io:5000/saderi/php-nginx:7.4-fpm
         docker push cloud.canister.io:5000/saderi/php-nginx:7.4-fpm
         

